name: ir_analysis
channels:
  - defaults
dependencies:
  - python=3.7.7
  - pip==20.0.2
  - pip:
    - alembic==1.4.2
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.5
    - click==7.1.2
    - cliff==3.1.0
    - cmaes==0.5.0
    - cmd2==0.8.9
    - colorama==0.4.3
    - colorlog==4.1.0
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - importlib-metadata==1.6.1
    - ipykernel==5.3.0
    - ipython==7.15.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - jinja2==2.11.2
    - joblib==0.15.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - kiwisolver==1.2.0
    - lightgbm==2.3.1
    - mako==1.1.3
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - notebook==6.0.3
    - numpy==1.18.4
    - optuna==1.5.0
    - packaging==20.4
    - pandas==1.0.4
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pbr==5.4.5
    - pickleshare==0.7.5
    - prettytable==0.7.2
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.5
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyperclip==1.8.0
    - pyreadline==2.1
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - pytz==2020.1
    - pywin32==227
    - pywinpty==0.5.7
    - pyyaml==5.3.1
    - pyzmq==19.0.1
    - qtconsole==4.7.4
    - qtpy==1.9.0
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - seaborn==0.10.1
    - send2trash==1.5.0
    - six==1.15.0
    - sqlalchemy==1.3.17
    - stevedore==2.0.0
    - terminado==0.8.3
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tornado==6.0.4
    - tqdm==4.46.0
    - traitlets==4.3.3
    - wcwidth==0.2.3
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.1.0

